/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import utility.BDUtility;

/**
 *
 * @author mosb2
 */
public class Admin_page extends javax.swing.JFrame {

    /**
     * Creates new form choose
     */
    public Admin_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_btm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        new_class = new javax.swing.JButton();
        AllStudent = new javax.swing.JButton();
        Del_stu = new javax.swing.JButton();
        Reg_doc = new javax.swing.JButton();
        Del_doc = new javax.swing.JButton();
        upd_stu = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        AllDoctors = new javax.swing.JButton();
        Reg_stu2 = new javax.swing.JButton();
        Assigned_Class = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 624));
        setMinimumSize(new java.awt.Dimension(1200, 624));
        setUndecorated(true);

        Exit_btm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit_btm.setText("X");
        Exit_btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Attendance System");

        new_class.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        new_class.setText("Create New Class");
        new_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_classActionPerformed(evt);
            }
        });

        AllStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllStudent.setText("Show All Students");
        AllStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllStudentActionPerformed(evt);
            }
        });

        Del_stu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Del_stu.setText("Delete Student");
        Del_stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_stuActionPerformed(evt);
            }
        });

        Reg_doc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reg_doc.setText("Register Doctor");
        Reg_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg_docActionPerformed(evt);
            }
        });

        Del_doc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Del_doc.setText("Delete Doctor");
        Del_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_docActionPerformed(evt);
            }
        });

        upd_stu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        upd_stu.setText("Update Student");
        upd_stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_stuActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        AllDoctors.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllDoctors.setText("Show All Doctors");
        AllDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDoctorsActionPerformed(evt);
            }
        });

        Reg_stu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reg_stu2.setText("Register Student");
        Reg_stu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg_stu2ActionPerformed(evt);
            }
        });

        Assigned_Class.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Assigned_Class.setText("Assign Class");
        Assigned_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assigned_ClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(logout)
                .addGap(207, 1091, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365)
                        .addComponent(Exit_btm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Assigned_Class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(new_class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AllDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Del_doc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Reg_doc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AllStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                            .addComponent(upd_stu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Reg_stu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Del_stu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit_btm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addComponent(Reg_stu2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upd_stu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Del_stu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AllStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Reg_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Del_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AllDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(new_class, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Assigned_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(logout)
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_btmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btmActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_Exit_btmActionPerformed

    private void new_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_classActionPerformed
        BDUtility.openForm(NewClass.class.getSimpleName(), new NewClass());
       
    }//GEN-LAST:event_new_classActionPerformed

    private void AllStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllStudentActionPerformed
        BDUtility.openForm(Stu_view.class.getSimpleName(), new Stu_view());   
    }//GEN-LAST:event_AllStudentActionPerformed

    private void Del_stuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_stuActionPerformed
    BDUtility.openForm(Stu_Delete.class.getSimpleName(), new Stu_Delete());
    }//GEN-LAST:event_Del_stuActionPerformed

    private void Reg_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg_docActionPerformed
        // TODO add your handling code here:
        BDUtility.openForm(Doc_Reg.class.getSimpleName(), new Doc_Reg());
    }//GEN-LAST:event_Reg_docActionPerformed

    private void Del_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_docActionPerformed
        // TODO add your handling code here:
    BDUtility.openForm(Doc_Delete.class.getSimpleName(), new Doc_Delete());
    }//GEN-LAST:event_Del_docActionPerformed

    private void upd_stuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_stuActionPerformed
        // TODO add your handling code here:
        BDUtility.openForm(Stu_Update.class.getSimpleName(), new Stu_Update());
        
    }//GEN-LAST:event_upd_stuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        BDUtility.openForm(Login.class.getSimpleName(), new Login());;
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void AllDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDoctorsActionPerformed
        BDUtility.openForm(Doc_view.class.getSimpleName(), new Doc_view()); 
    }//GEN-LAST:event_AllDoctorsActionPerformed

    private void Reg_stu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg_stu2ActionPerformed
        // TODO add your handling code here:
        BDUtility.openForm(Stu_Reg.class.getSimpleName(), new Stu_Reg());        
    }//GEN-LAST:event_Reg_stu2ActionPerformed

    private void Assigned_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assigned_ClassActionPerformed
        BDUtility.openForm(AssignClass.class.getSimpleName(), new AssignClass());        
    }//GEN-LAST:event_Assigned_ClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllDoctors;
    private javax.swing.JButton AllStudent;
    private javax.swing.JButton Assigned_Class;
    private javax.swing.JButton Del_doc;
    private javax.swing.JButton Del_stu;
    private javax.swing.JButton Exit_btm;
    private javax.swing.JButton Reg_doc;
    private javax.swing.JButton Reg_stu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton new_class;
    private javax.swing.JButton upd_stu;
    // End of variables declaration//GEN-END:variables
}
